service: checkSitemaps-service
frameworkVersion: '3'

# custom:
#     serverless-offline:
#         httpPort: 4000
#         websocketPort: 4001
#         lambdaPort: 4002

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  checksitemaps:
    handler: api/app.handler
    timeout: 900 # Set the appropriate timeout in seconds
    events:
      - httpApi:
          path: /api/check-urls
          method: ANY

plugins:
  - serverless-offline